<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cmcd"
 *
 * Auto generated by Extension Builder 2017-01-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'CD Verwaltung',
	'description' => 'A tool to manage CDs',
	'category' => 'plugin',
	'author' => 'Christian Marquardt',
	'author_email' => 'christian.marquardt11@gmx.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0,.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);